name: Deploy Specific Folder to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy specific folder to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          local: /home/runner/work/orbitalsolutions-frontend/orbitalsolutions-frontend/src/public
          remote: /var/www/html/orbitalsolutions.ca/public/
