name: Deploy Specific Folder to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy specific folder to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rsync -avz ${{ github.workspace }}/src/public bot@chicago-webserver-node-1.orbitalsolutions.ca:/var/www/html/orbitalsolutions.ca/public/
