name: Deploy Specific Folder to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy specific folder to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          fingerprint: ${{ secrets.SERVER_FINGERPRINT }}
          script: rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" /home/runner/work/orbitalsolutions-frontend/orbitalsolutions-frontend/src/public ***@***:/var/www/html/orbitalsolutions.ca/public/
