name: Deploy Specific Folder to Server

on:
  push:
    branches:
      - prod
      - qa
  pull_request:
    types: [ready_for_review]

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deployment to the first prod server
      - name: Deploy specific folder to first prod server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.CHICAGO_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          ssh_private_key: ${{ secrets.CHICAGO_SSH_KEY }}
          local_path: "./src/public/*"
          remote_path: "/var/www/html/first-prod-server/public"
          args: "-o ConnectTimeout=5"

      # Deployment to the second prod server
      - name: Deploy specific folder to second prod server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.TORONTO_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          ssh_private_key: ${{ secrets.TORONTO_SSH_KEY }}
          local_path: "./src/public/*"
          remote_path: "/var/www/html/second-prod-server/public"
          args: "-o ConnectTimeout=5"

  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy specific folder to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.CHICAGO_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          ssh_private_key: ${{ secrets.CHICAGO_SSH_KEY }}
          local_path: "./src/public/*"
          remote_path: "/var/www/html/orbitalsolutions.ca/beta"
          args: "-o ConnectTimeout=5"

      - name: Deploy specific folder to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.TORONTO_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          ssh_private_key: ${{ secrets.TORONTO_SSH_KEY }}
          local_path: "./src/public/*"
          remote_path: "/var/www/html/orbitalsolutions.ca/beta"
          args: "-o ConnectTimeout=5"

  deploy-dev:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy specific folder to first dev server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.CHICAGO_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          ssh_private_key: ${{ secrets.CHICAGO_SSH_KEY }}
          local_path: "./src/public/*"
          remote_path: "/var/www/html/orbitalsolutions.ca/dev"
          args: "-o ConnectTimeout=5"

      - name: Deploy specific folder to second dev server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.TORONTO_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          ssh_private_key: ${{ secrets.TORONTO_SSH_KEY }}
          local_path: "./src/public/*"
          remote_path: "/var/www/html/orbitalsolutions.ca/dev"
          args: "-o ConnectTimeout=5"
