name: Deploy Specific Folder to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy specific folder to server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }} # Assuming you're using a password for SFTP. If you're using a key, this action might not be suitable.
          port: ${{ secrets.SERVER_PORT }}
          protocol: sftp
          server-dir: /var/www/html/orbitalsolutions.ca/public/
          local-dir: ./src/public/
