name: "UI Deploy"

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "Deployment environment (e.g., dev, qa, prod)"
        required: true
        type: string
      DEPLOY_PATH:
        description: "Deployment Path on Server"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: "Deployment environment (e.g., dev, qa, prod)"
        required: true
        type: string
      DEPLOY_PATH:
        description: "Deployment Path on Server"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }} # Assuming you have a 'SERVER_USER' secret set up
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./src/public/*" # Update this path according to your project structure
          remote_path: ${{ inputs.DEPLOY_PATH }}
          args: "-o ConnectTimeout=5"
