name: "UI Deploy"

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "Deployment environment (e.g., dev, qa, prod)"
        required: true
        type: string
      DEPLOY_PATH:
        description: "Deployment Path on Server"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: "Deployment environment (e.g., dev, qa, prod)"
        required: true
        type: string
      DEPLOY_PATH:
        description: "Deployment Path on Server"
        required: true
        type: string
      SERVER_PASSWORD:
        description: "Server Password"
        required: true
        type: string
      SERVER_HOST:
        description: "Server Host"
        required: true
        type: string
      SERVER_SSH_KEY:
        description: "Server SSH Key"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ inputs.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }} # Assuming you have a 'SERVER_USER' secret set up
          ssh_private_key: ${{ inputs.SERVER_SSH_KEY }}
          local_path: "./src/public/*" # Update this path according to your project structure
          remote_path: ${{ inputs.DEPLOY_PATH }}
          sftpArgs: "-o ConnectTimeout=5"
          port: 22
          password: ${{ inputs.SERVER_PASSWORD }}
