name: UI Deployment

on:
  push:
    branches: [dev, "release/OrbitalSolutions-*"]
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SSH_PRIVATE_KEY: ${{ secrets.CHICAGO_SSH_KEY }}
      SERVER_HOST: ${{ secrets.CHICAGO_SERVER_HOST }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
    steps:
      - name: Call reusable workflow for Dev
        uses: ./.github/workflows/ui-deploy.yml
        with:
          ENVIRONMENT: dev
          DEPLOY_PATH: "/var/www/html/dev.orbitalsolutions.ca/public"
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ env.SERVER_HOST }}
          SERVER_PASSWORD: ${{ env.SERVER_PASSWORD }}

  deploy_qa:
    name: Deploy QA
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SSH_PRIVATE_KEY: ${{ secrets.CHICAGO_SSH_KEY }}
      SERVER_HOST: ${{ secrets.CHICAGO_SERVER_HOST }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
    steps:
      - name: Call reusable workflow for QA
        uses: ./.github/workflows/ui-deploy.yml
        with:
          ENVIRONMENT: dev
          DEPLOY_PATH: "/var/www/html/beta.orbitalsolutions.ca/public"
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ env.SERVER_HOST }}
          SERVER_PASSWORD: ${{ env.SERVER_PASSWORD }}

  deploy_prod:
    name: Deploy Prod
    needs: deploy_qa
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SSH_PRIVATE_KEY: ${{ secrets.CHICAGO_SSH_KEY }}
      SERVER_HOST: ${{ secrets.CHICAGO_SERVER_HOST }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
    steps:
      - name: Call reusable workflow for Prod
        uses: ./.github/workflows/ui-deploy.yml
        with:
          ENVIRONMENT: dev
          DEPLOY_PATH: "/var/www/html/orbitalsolutions.ca/public"
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ env.SERVER_HOST }}
          SERVER_PASSWORD: ${{ env.SERVER_PASSWORD }}
