name: UI Deployment

on:
  push:
    branches: [dev, "release/OrbitalSolutions-*"]
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy Dev
    uses: ./.github/workflows/ui-deploy.yml
    with:
      ENVIRONMENT: dev
      DEPLOY_PATH: "/var/www/html/dev.orbitalsolutions.ca/public"

  deploy_qa:
    name: Deploy QA
    uses: ./.github/workflows/ui-deploy.yml
    with:
      ENVIRONMENT: qa
      DEPLOY_PATH: "/var/www/html/beta.orbitalsolutions.ca/public"

  deploy_prod:
    name: Deploy Prod
    needs: deploy_qa
    uses: ./.github/workflows/ui-deploy.yml
    with:
      ENVIRONMENT: prod
      DEPLOY_PATH: "/var/www/html/orbitalsolutions.ca/public"
